#!/usr/bin/env python3
"""Generate an explicit Serious Engine entity symbol registry translation unit."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

SYMBOL_RE = re.compile(
    r'extern\s+"C"\s+DECL_DLL\s+CDLLEntityClass\s+'
    r'([A-Za-z_][A-Za-z0-9_]*_DLLClass)\s*;'
)


def discover_symbols(root: Path) -> list[str]:
    symbols: set[str] = set()
    for header in root.rglob("*.h"):
        text = header.read_text(encoding="utf-8", errors="ignore")
        symbols.update(SYMBOL_RE.findall(text))
    return sorted(symbols)


def render(encounter: str, symbols: list[str]) -> str:
    prefix = f"SeriousIOS_{encounter}"
    declarations = "\n".join(
        f'extern "C" CDLLEntityClass {symbol};' for symbol in symbols
    )
    registrations = "\n".join(
        "    ok = SeriousIOS_RegisterStaticSymbol("
        f'"{symbol}", static_cast<void*>(&{symbol})) && ok;'
        for symbol in symbols
    )
    return f'''// Generated by scripts/generate_static_entity_registry.py.
// Do not edit manually.

#include "SeriousIOSStaticRegistry.h"

#include <cstddef>

class CDLLEntityClass;

{declarations}

extern "C" bool {prefix}_RegisterEntitySymbols() noexcept {{
    bool ok = true;
{registrations}
    return ok;
}}

extern "C" std::size_t {prefix}_EntitySymbolCount() noexcept {{
    return {len(symbols)};
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("generated_root", type=Path)
    parser.add_argument("encounter", choices=("TFE", "TSE"))
    parser.add_argument("output", type=Path)
    parser.add_argument("--manifest", type=Path)
    args = parser.parse_args()

    root = args.generated_root.resolve()
    if not root.is_dir():
        raise SystemExit(f"generated root does not exist: {root}")

    symbols = discover_symbols(root)
    if len(symbols) < 100:
        raise SystemExit(
            f"expected a complete entity corpus, found only {len(symbols)} symbols"
        )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(args.encounter, symbols), encoding="utf-8")

    manifest_path = args.manifest or args.output.with_suffix(".json")
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(
            {
                "encounter": args.encounter,
                "generated_root": str(root),
                "symbol_count": len(symbols),
                "symbols": symbols,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    print(f"{args.encounter}: generated registry for {len(symbols)} entity symbols")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
