#!/usr/bin/env python3
"""Generate an explicit Serious Engine entity symbol registry translation unit."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

SYMBOL_RE = re.compile(
    r'extern\s+"C"\s+DECL_DLL\s+CDLLEntityClass\s+'
    r'([A-Za-z_][A-Za-z0-9_]*_DLLClass)\s*;'
)
ENTITY_RE = re.compile(r"(?m)^\s*entity\(\s*([^\s)#]+)\s*\)")

ENCOUNTER_PACKAGES = {
    "TFE": ("Engine/Classes/", "Entities/"),
    "TSE": ("Engine/Classes/", "EntitiesMP/"),
}


def selected_entities(upstream: Path, encounter: str) -> list[str]:
    cmake = upstream / f"Sam{encounter}" / "Sources" / "CMakeLists.txt"
    if not cmake.is_file():
        raise FileNotFoundError(cmake)

    text = cmake.read_text(encoding="utf-8", errors="replace")
    # Remove line comments so dormant examples cannot enter the static registry.
    uncommented = "\n".join(line.split("#", 1)[0] for line in text.splitlines())
    prefixes = ENCOUNTER_PACKAGES[encounter]
    selected = sorted(
        {
            entity
            for entity in ENTITY_RE.findall(uncommented)
            if entity.startswith(prefixes)
        }
    )
    if len(selected) < 100:
        raise RuntimeError(
            f"{encounter}: expected a complete CMake-selected entity set, "
            f"found only {len(selected)} entries"
        )
    return selected


def discover_symbols(
    generated_root: Path,
    upstream: Path,
    encounter: str,
) -> tuple[list[str], list[str]]:
    entities = selected_entities(upstream, encounter)
    symbol_by_entity: dict[str, str] = {}

    for entity in entities:
        header = generated_root / f"{entity}.h"
        if not header.is_file():
            raise FileNotFoundError(
                f"{encounter}: generated header missing for CMake entity {entity}: {header}"
            )
        matches = sorted(set(SYMBOL_RE.findall(header.read_text(encoding="utf-8", errors="ignore"))))
        if len(matches) != 1:
            raise RuntimeError(
                f"{encounter}: expected one DLLClass export in {header}, found {matches}"
            )
        symbol_by_entity[entity] = matches[0]

    symbols = sorted(set(symbol_by_entity.values()))
    if len(symbols) != len(symbol_by_entity):
        duplicates: dict[str, list[str]] = {}
        for entity, symbol in symbol_by_entity.items():
            duplicates.setdefault(symbol, []).append(entity)
        repeated = {symbol: paths for symbol, paths in duplicates.items() if len(paths) > 1}
        raise RuntimeError(f"{encounter}: duplicate entity exports: {repeated}")

    return symbols, entities


def render(encounter: str, symbols: list[str]) -> str:
    prefix = f"SeriousIOS_{encounter}"
    declarations = "\n".join(
        f'extern "C" CDLLEntityClass {symbol};' for symbol in symbols
    )
    registrations = "\n".join(
        "    ok = SeriousIOS_RegisterStaticSymbol("
        f'"{symbol}", static_cast<void*>(&{symbol})) && ok;'
        for symbol in symbols
    )
    return f'''// Generated by scripts/generate_static_entity_registry.py.
// Do not edit manually.

#include "SeriousIOSStaticRegistry.h"

#include <cstddef>

class CDLLEntityClass;

{declarations}

extern "C" bool {prefix}_RegisterEntitySymbols() noexcept {{
    bool ok = true;
{registrations}
    return ok;
}}

extern "C" std::size_t {prefix}_EntitySymbolCount() noexcept {{
    return {len(symbols)};
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("generated_root", type=Path)
    parser.add_argument("encounter", choices=("TFE", "TSE"))
    parser.add_argument("output", type=Path)
    parser.add_argument("--upstream", type=Path, required=True)
    parser.add_argument("--manifest", type=Path)
    args = parser.parse_args()

    root = args.generated_root.resolve()
    upstream = args.upstream.resolve()
    if not root.is_dir():
        raise SystemExit(f"generated root does not exist: {root}")
    if not upstream.is_dir():
        raise SystemExit(f"upstream root does not exist: {upstream}")

    symbols, entities = discover_symbols(root, upstream, args.encounter)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(args.encounter, symbols), encoding="utf-8")

    manifest_path = args.manifest or args.output.with_suffix(".json")
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(
            {
                "encounter": args.encounter,
                "generated_root": str(root),
                "upstream_root": str(upstream),
                "selected_entity_count": len(entities),
                "selected_entities": entities,
                "symbol_count": len(symbols),
                "symbols": symbols,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    print(
        f"{args.encounter}: generated registry for {len(symbols)} "
        f"CMake-selected entity symbols"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
