#!/usr/bin/env python3
"""Generate Game and shader registrations for a statically linked encounter."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

MAIN_RE = re.compile(r"\bSHADER_MAIN\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)")
DESC_RE = re.compile(r"\bSHADER_DESC\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*,")


def discover_shader_names(source_root: Path) -> list[str]:
    main_names: set[str] = set()
    desc_names: set[str] = set()
    for source in sorted((source_root / "Shaders").glob("*.cpp")):
        text = source.read_text(encoding="utf-8", errors="ignore")
        main_names.update(MAIN_RE.findall(text))
        desc_names.update(DESC_RE.findall(text))

    if main_names != desc_names:
        raise RuntimeError(
            "shader entry/descriptor mismatch: "
            f"main-only={sorted(main_names - desc_names)}, "
            f"desc-only={sorted(desc_names - main_names)}"
        )
    if len(main_names) < 10:
        raise RuntimeError(f"expected a complete shader set, found {len(main_names)}")
    return sorted(main_names)


def render(encounter: str, shader_names: list[str]) -> str:
    prefix = f"SeriousIOS_{encounter}"
    declarations: list[str] = [
        "class CGame;",
        "struct ShaderDesc;",
        'extern "C" CGame* GAME_Create(void);',
    ]
    registrations = [
        '    ok = SeriousIOS_RegisterStaticSymbol("GAME_Create", '
        'SeriousIOS_FunctionAddress(&GAME_Create)) && ok;'
    ]

    for name in shader_names:
        declarations.extend(
            [
                f'extern "C" void Shader_{name}(void);',
                f'extern "C" void Shader_Desc_{name}(ShaderDesc&);',
            ]
        )
        registrations.extend(
            [
                f'    ok = SeriousIOS_RegisterStaticSymbol("Shader_{name}", '
                f'SeriousIOS_FunctionAddress(&Shader_{name})) && ok;',
                f'    ok = SeriousIOS_RegisterStaticSymbol("Shader_Desc_{name}", '
                f'SeriousIOS_FunctionAddress(&Shader_Desc_{name})) && ok;',
            ]
        )

    return f'''// Generated by scripts/generate_static_runtime_registry.py.
// Do not edit manually.

#include "SeriousIOSStaticRegistry.h"

#include <cstddef>
#include <cstring>

{chr(10).join(declarations)}

template <typename Function>
static void* SeriousIOS_FunctionAddress(Function function) noexcept {{
    static_assert(sizeof(Function) == sizeof(void*),
                  "iOS function and data pointers must have matching size");
    void* address = nullptr;
    std::memcpy(&address, &function, sizeof(address));
    return address;
}}

extern "C" bool {prefix}_RegisterRuntimeSymbols() noexcept {{
    bool ok = true;
{chr(10).join(registrations)}
    return ok;
}}

extern "C" std::size_t {prefix}_RuntimeSymbolCount() noexcept {{
    return {1 + len(shader_names) * 2};
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("upstream", type=Path)
    parser.add_argument("encounter", choices=("TFE", "TSE"))
    parser.add_argument("output", type=Path)
    parser.add_argument("--manifest", type=Path)
    args = parser.parse_args()

    upstream = args.upstream.resolve()
    source_root = upstream / f"Sam{args.encounter}" / "Sources"
    if not source_root.is_dir():
        raise FileNotFoundError(source_root)

    shader_names = discover_shader_names(source_root)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(args.encounter, shader_names), encoding="utf-8")

    manifest = {
        "encounter": args.encounter,
        "game_symbols": ["GAME_Create"],
        "shader_count": len(shader_names),
        "shader_names": shader_names,
        "symbol_count": 1 + len(shader_names) * 2,
    }
    manifest_path = args.manifest or args.output.with_suffix(".json")
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(
        f"{args.encounter}: generated Game + {len(shader_names)} shader pairs "
        f"({manifest['symbol_count']} symbols)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
